spring:
  config:
    import: "classpath:key.yml"
  elasticsearch:
    rest:
      uris: ${instance}
      username: ${instanceUN}
      password: ${instancePW}
  data:
    elasticsearch:
      repositories:
        enabled: false